CREATE SCHEMA IF NOT EXISTS PCINFO AUTHORIZATION sa;

CREATE TABLE IF NOT EXISTS SKU(SKU_ID INT auto_increment NOT NULL, NAME VARCHAR(255),DESCRIPTION VARCHAR(255),RETAIL_PRICE VARCHAR(10),SALE_PRICE VARCHAR(10),INVENTORY_TYPE VARCHAR(40),QUANTITY_AVAILABLE VARCHAR(471),FULFILLMENT_TYPE_ID INT,PRODUCT_ID INT);


